const DATA_SOURCE = [
  {
    "Food Group": "Red Meat",
    "GHG (kg CO2e/kg)": 60,
    "Water Use (kl/kg)": 15.4,
    "Land Use (m2/kg)": 320,
    "Eutrophication (g PO4 eq/kg)": 200,
    "Acidification (g SO2 eq/kg)": 300,
    "Default Global Per Capita Consumption (kg/year)": 26.88,
    "Global Farmed Animals Killed / Year": 0.07,
    "Average Dressed Weight (kg)": 384,
    "Compensation Factor": -1,
    "Land Biodiversity Loss at Baseline Diet*": 0.129024,
    "Total Land Impact (m2) in a 0% plant based scenario": 8601.6
  },
  {
    "Food Group": "Pig Meat",
    "GHG (kg CO2e/kg)": 6,
    "Water Use (kl/kg)": 6,
    "Land Use (m2/kg)": 45,
    "Eutrophication (g PO4 eq/kg)": 50,
    "Acidification (g SO2 eq/kg)": 70,
    "Default Global Per Capita Consumption (kg/year)": 22.54,
    "Global Farmed Animals Killed / Year": 0.23,
    "Average Dressed Weight (kg)": 98,
    "Compensation Factor": -1,
    "Land Biodiversity Loss at Baseline Diet*": 0.0152145,
    "Total Land Impact (m2) in a 0% plant based scenario": 1014.3
  },
  {
    "Food Group": "Poultry",
    "GHG (kg CO2e/kg)": 7,
    "Water Use (kl/kg)": 4.3,
    "Land Use (m2/kg)": 50,
    "Eutrophication (g PO4 eq/kg)": 70,
    "Acidification (g SO2 eq/kg)": 80,
    "Default Global Per Capita Consumption (kg/year)": 32.5,
    "Global Farmed Animals Killed / Year": 13,
    "Average Dressed Weight (kg)": 2.5,
    "Compensation Factor": -1,
    "Land Biodiversity Loss at Baseline Diet*": 0.03375,
    "Total Land Impact (m2) in a 0% plant based scenario": 2250
  },
  {
    "Food Group": "Fish & Seafood",
    "GHG (kg CO2e/kg)": 6,
    "Water Use (kl/kg)": 1.5,
    "Land Use (m2/kg)": 30,
    "Eutrophication (g PO4 eq/kg)": 50,
    "Acidification (g SO2 eq/kg)": 60,
    "Default Global Per Capita Consumption (kg/year)": 0.3,
    "Global Farmed Animals Killed / Year": 32,
    "Average Dressed Weight (kg)": 2,
    "Compensation Factor": -1,
    "Land Biodiversity Loss at Baseline Diet*": 0.001512,
    "Total Land Impact (m2) in a 0% plant based scenario": 100.8
  },
  {
    "Food Group": "Dairy",
    "GHG (kg CO2e/kg)": 3.5,
    "Water Use (kl/kg)": 1,
    "Land Use (m2/kg)": 50,
    "Eutrophication (g PO4 eq/kg)": 40,
    "Acidification (g SO2 eq/kg)": 50,
    "Default Global Per Capita Consumption (kg/year)": 80.64,
    "Global Farmed Animals Killed / Year": 0.15,
    "Average Dressed Weight (kg)": 384,
    "Compensation Factor": -1,
    "Land Biodiversity Loss at Baseline Diet*": 0.06048,
    "Total Land Impact (m2) in a 0% plant based scenario": 4032
  },
  {
    "Food Group": "Eggs",
    "GHG (kg CO2e/kg)": 4.5,
    "Water Use (kl/kg)": 3.3,
    "Land Use (m2/kg)": 40,
    "Eutrophication (g PO4 eq/kg)": 50,
    "Acidification (g SO2 eq/kg)": 60,
    "Default Global Per Capita Consumption (kg/year)": 13,
    "Global Farmed Animals Killed / Year": 0.21,
    "Average Dressed Weight (kg)": 2.5,
    "Compensation Factor": -1,
    "Land Biodiversity Loss at Baseline Diet*": 0.0078,
    "Total Land Impact (m2) in a 0% plant based scenario": 520
  },
  {
    "Food Group": "Legumes & Pulses",
    "GHG (kg CO2e/kg)": 1.5,
    "Water Use (kl/kg)": 4,
    "Land Use (m2/kg)": 3,
    "Eutrophication (g PO4 eq/kg)": 20,
    "Acidification (g SO2 eq/kg)": 20,
    "Default Global Per Capita Consumption (kg/year)": 8,
    "Global Farmed Animals Killed / Year": 0,
    "Average Dressed Weight (kg)": 0,
    "Compensation Factor": 0.5,
    "Land Biodiversity Loss at Baseline Diet*": 0.00036,
    "Total Land Impact (m2) in a 0% plant based scenario": 24
  },
  {
    "Food Group": "Nuts & Seeds",
    "GHG (kg CO2e/kg)": 2.3,
    "Water Use (kl/kg)": 9,
    "Land Use (m2/kg)": 7,
    "Eutrophication (g PO4 eq/kg)": 30,
    "Acidification (g SO2 eq/kg)": 30,
    "Default Global Per Capita Consumption (kg/year)": 4,
    "Global Farmed Animals Killed / Year": 0,
    "Average Dressed Weight (kg)": 0,
    "Compensation Factor": 0.2,
    "Land Biodiversity Loss at Baseline Diet*": 0.00042,
    "Total Land Impact (m2) in a 0% plant based scenario": 28
  },
  {
    "Food Group": "Vegetables",
    "GHG (kg CO2e/kg)": 0.8,
    "Water Use (kl/kg)": 0.3,
    "Land Use (m2/kg)": 2,
    "Eutrophication (g PO4 eq/kg)": 10,
    "Acidification (g SO2 eq/kg)": 10,
    "Default Global Per Capita Consumption (kg/year)": 110,
    "Global Farmed Animals Killed / Year": 0,
    "Average Dressed Weight (kg)": 0,
    "Compensation Factor": 0.3,
    "Land Biodiversity Loss at Baseline Diet*": 0.0033,
    "Total Land Impact (m2) in a 0% plant based scenario": 220
  },
  {
    "Food Group": "Fruits",
    "GHG (kg CO2e/kg)": 1.1,
    "Water Use (kl/kg)": 1,
    "Land Use (m2/kg)": 2,
    "Eutrophication (g PO4 eq/kg)": 10,
    "Acidification (g SO2 eq/kg)": 10,
    "Default Global Per Capita Consumption (kg/year)": 80,
    "Global Farmed Animals Killed / Year": 0,
    "Average Dressed Weight (kg)": 0,
    "Compensation Factor": 0.2,
    "Land Biodiversity Loss at Baseline Diet*": 0.0024,
    "Total Land Impact (m2) in a 0% plant based scenario": 160
  },
  {
    "Food Group": "Grains & Cereals",
    "GHG (kg CO2e/kg)": 1,
    "Water Use (kl/kg)": 1.5,
    "Land Use (m2/kg)": 5,
    "Eutrophication (g PO4 eq/kg)": 20,
    "Acidification (g SO2 eq/kg)": 20,
    "Default Global Per Capita Consumption (kg/year)": 110,
    "Global Farmed Animals Killed / Year": 0,
    "Average Dressed Weight (kg)": 0,
    "Compensation Factor": 0.1,
    "Land Biodiversity Loss at Baseline Diet*": 0.00825,
    "Total Land Impact (m2) in a 0% plant based scenario": 550
  }
]